title: J.Y's BLOG
subtitle: ''
description: 'Hello World'
keywords:
author: thisdk
language: zh-CN
timezone: 'Asia/Shanghai'


url: https://thisdk.github.io
permalink: :year/:month/:day/:title.html
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true


source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


new_post_name: :title.md
default_layout: post
titlecase: false


external_link:
  enable: true
  field: site
  exclude: ''


filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true


highlight:
  enable: true
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false


index_generator:
  path: ''
  per_page: 10
  order_by: -date


default_category: uncategorized
category_map:
tag_map:


meta_generator: true


date_format: YYYY-MM-DD
time_format: HH:mm:ss


updated_option: 'mtime'


per_page: 10
pagination_dir: page


include:
exclude:
ignore:


favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  android_manifest: /images/manifest.json


search:
  path: search.xml
  field: post
  content: true
  format: html


emoji:
  enable: true
  className: github-emoji
  styles:
  customEmojis:


theme: next


deploy:
  type: git
  repo: git@github.com:thisdk/thisdk.github.io.git
  branch: main
